### PR TITLE
Optimized inner loop iteration

### PR DESCRIPTION
**Pull request by gustf**
Gives 16-17% faster total calculation time on the longest tests on my
computer.

### CODE REVIEW

**Comment by addaleax** [comment]
Hey, thanks! Weirdly, this gives a bit of a slowdown on my configuration (g++ 5.2.1, Ubuntu 15.10, x64 AMD with everything up to AVX), although I can see no real reason for that.
I’ll try this on a few other systems I have access to and I’ll try and dig a little into the generated assembly code, but could you maybe specify a bit how you tested this?

**Comment by addaleax** [comment]
Got the same with clang, about ~10 % slowdown. Apparently, your code generates a lot of jumps, which kind of makes sense, which counteract the saved work here.

But yeah, you’ve got a point with moving the `+1` out of the `min()` blocks; I think that should definitely be done. It probably actually simplifies the SIMD code quite a bit, so there’s an additional advantage to doing the same thing there.

**Comment by addaleax** [comment]
You can see what I tried in bb688f5d – I didn’t want to commit to master until I know why this PR here leads to a performance gain for you and a loss on my machine :)

**Comment by gustf** [comment]
Ok, strange indeed! I will check this later today after work :)

Here is my configuration

```
[gustaf@gustf-air levenshtein-sse{master}]$ uname -a
Darwin gustf-air.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
[gustaf@gustf-air levenshtein-sse{master}]$ c++ --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
```

**Comment by gustf** [comment]
I tested with your changes in [bb688f5](https://github.com/addaleax/levenshtein-sse/commit/bb688f5d280da7c07f069f04716e669e130f021d), but I did could not see any big changes.
EDIT: I was comparing this to my optimized code on my setup, this is quite faster compared the "original" version :+1: 

However, I also got a slowdown with g++. (5.3.0) with my commit above, I do not know why either.
I did some more testing and optimizations and commit:ed a version that was faster with both compilers.

Tested with a `BIT_MIN(x,y)` (see below) version also, but did not really give any performance boost over `std::min(x,y)` so I used the "standard".

```
#define BIT_MIN(x,y) ((y) ^ (((x) ^ (y)) & -((x) < (y))))
```

Hope you get the same performance boost. 
I am running this on a macbook air (Intel Dual Core i7, SSE4.1/4.2, AVX 2.0) which is far from optimal, the CPU have turbo-boost (1.7-3.3 GHz) and it is hard to compare results when you can not know exactly how fast the CPU was running at the time.
Anyway, If you don't get any speedup it's probably better to leave it.

**Comment by addaleax** [comment]
Okay, so, I’m merging bb688f5 now. I don’t know if you are familiar with x86 assembly, but if you want, I can try and do some static analysis of your generated binaries to see what’s going on there (i.e. to see why using the `if(…)`-based version or the `BIT_MIN` version might be faster/slower).

And anyway, I don’t know what use cases you used for testing (`make`?), but for long strings, nearly all of the matrix is computed using SSE instructions, so changes in the `LevenshteinIterationBase` should not have too much of an effect there.

**Comment by addaleax** [comment]
One thing that _is_ cool, though: You have AVX2 enabled, which is unfortunately something no machine that I have access to provides.
In theory, using AVX2 should make some things twice as fast as the current SSE4.1/SSSE3-based SIMD code since AVX registers have twice as many lanes as SSE ones. If you are interested in testing (or if you are familiar with the intrinsics yourself?), I could try and implement that to gain a larger speedup for larger strings (>= 32 bytes)?

**Comment by addaleax** [comment]
And don’t take this like I don’t see the point in your proposed change: I’d just like to understand _why_ the result will be significantly faster. I completely believe you when you say it is :)

**Comment by gustf** [comment]
Ok cool about the merge! And I totally understand not merge:ing something that you don't know really is an improvement. One guess is that its AMD/Intel differences?

About AVX2, I could test an implementation if you want :) I am unfortunately not familiar enough with the intrinsics to implement this myself.

But it is pretty interesting, I think, that I can change the non-SSE function and get a total speedup of 16-17%. It could indicate that the total time of calculating the corner cases (non-SSE) is taking a somewhat large percent of the total calculation time.
Maybe implement many SSE-functions, i.e 32-way(AVX2), 16-way, 8-way, 4-way. And then call them accordingly in the `performSIMD` depending of the value of `i` and `bLen - j`? This might minimize the time it spends in the slow non-SSE function. Do you think this would work, or is it a bad idea?

**Comment by addaleax** [comment]
Hm, I tried comparing the tests between this PR’s head and its base on one of the servers where I’m admin. It’s also an Intel (i7, with everything up to SSE4.2), and I can see some improvement, but it’s more in the range of 2–3%.

I think I’m going to merge this here anyway; This library should be able to compute Levenshtein distances between containers with arbitrary member types, and saving comparisons for what are possibly quite complex objects sounds like a good idea.

Regarding your last suggestion: Something along these lines would probably the best idea anyway, yes, but I guess the code might need some restructuring (I don’t really like my own case distinction [depending on `sizeof(T)` there](https://github.com/addaleax/levenshtein-sse/blob/73d1ce42cb676629d4ea21eb160d387adf2d1796/levenshtein-sse.hpp#L285) anyway). 
Since input may come in different sizes, there would be a total of |{4, 8, 16, 32} × {1, 2, 4}| = 12 different code paths for this solution, so I’ll probably have to come up with a bit of clever template mechanics there… I’ll see what I can do. :)

One thing I’m not 100 % sure about is how well AVX2 will mix with the SSE instructions; I think I remember hearing that switching between using the 256-bit versions and the 128-bit versions of the registers will result in degraded performance, but I don’t know if and how exactly that will have an impact here.

**Comment by addaleax** [comment]
Merged this in f205f3a71c13434f55e743ea5709e0d36d68bdfc.

**Comment by gustf** [comment]
Cool! 
And I am looking forward to see what you come up with with the template mechanism, and of course what the speedup will be :+1: 

I will put some thoughts about how to utilize multi-core when I find the time :)

**Comment by gustf** [comment]
Oh, sorry. Did not answer some of your questions:

No need to check diffs between `BIT_MIN` and `std:min`, at least not for my sake :)

The make commands I run is 
c++

```
[gustaf@gustf-air levenshtein-sse{master}]$ make clean all
rm -f test/test
c++ -O3 -DNDEBUG -march=native -std=c++11 -Wall -Wextra -Wno-unused-parameter  -I. -o test/test test/test.cpp
```

and for g++

```
[gustaf@gustf-air levenshtein-sse{master}]$ make clean all CXX=g++-5
rm -f test/test
g++-5 -O3 -DNDEBUG -march=native -std=c++11 -Wall -Wextra -Wno-unused-parameter  -I. -o test/test test/test.cpp
```

And I used the result from these tests when comparing

```
A = test/assets/loremipsum_1-64k.utf8
B = test/assets/loremipsum_2-64k.utf8
T = c
distance = 49618, expected = 49618
Time: 2403 ms
A = test/assets/loremipsum_1-64k.utf16
B = test/assets/loremipsum_2-64k.utf16
T = s
distance = 49607, expected = 49607
Time: 2716 ms
```

**Comment by addaleax** [comment]
Mh, you did not compare the `2403 ms` vs the `2716 ms` here, right? One of them is for `char` (`T = c`, the utf8 file) and one of them is for `short` (`T = s`, utf16), so it’s expectable that they lead to different timing results.

And yes, some way of optional support for multi-core parallelization would be great, but I’m not sure on what level that would best be done… but it’s definitely possible. :)

**Comment by gustf** [comment]
Not sure what you are asking me. Are you asking if I compared different test cases with each other, then the answer is no. I am comparing these 2 test results between different test runs. Would not make much sense otherwise hehe. :) I am using these ones as they are the comparing large strings.

**Comment by addaleax** [comment]
Ah, everything okay then – was just confused because you posted only one of the test run outputs :)

**Comment by gustf** [comment]
:)

**Comment by addaleax** [comment]
Btw, are you having a specific use case for the optimizations here in mind? I think there’s quite a bit of algorithmic optimization possible if you have some more information about the underlying data, e.g. an upper bound on their Levenshtein distance or something like that

**Comment by gustf** [comment]
Actually no, I do not use this at all myself. We had a competition for fun at work to make the fastest levenshtein implementation in JS. And I implemented one [quite a bit faster](http://jsperf.com/levenshtein-distance/25) than anything I could find anywere. 
And then I stumbled upon your library and got interested :)

About the upper bound, that could really speed things up in use cases where a limit can be provided.

**Comment by gustf** [comment]
I did an experiment with an AVX2 version that used both 32-way and 16-way. Haven't got it to do the calculation correctly but I think it is doing the same amount of work as a correct one would. Anyway, the result indicated a speedup of around ~35%. :)

**Comment by addaleax** [comment]
Oh, cool :) If you want me to look over it, you can always push your commits. And anway, I’m afraid I won’t have much time to work on this today, so for now it’s all yours :)

**Comment by gustf** [comment]
Did some more work, but unfortunately it still does not work. Would be awesome if you could look it over when you have the time. :)

Here is the [commit](https://github.com/gustf/levenshtein-sse/commit/29290d7a2262218920f0672ac9669b9ce116caeb). I have focused on getting the char-version working first.

**Comment by addaleax** [comment]
So, thanks to @PeterUstinox who offered me some time compiling & testing on his machine, I think I got the AVX2 support working (and there, it even provides very close to 50 % overall speedup for the tests!). You can checkout my changes in the avx2-support branch here ([current HEAD](https://github.com/addaleax/levenshtein-sse/commit/30dba3cf714d7ee93dd7963151dc3d0ae970107d)).

The main problem I encountered was that many AVX instructions (shuffle, unpack, align, etc.) work in 2 independent 128-bit lanes, so there were some adjustments necessary; I’d be glad if you could check out the changes? Everything, including support for 2- and 4-byte values, seems to work for me now :)

**Comment by gustf** [comment]
Ah, awesome! 
I noticed that the 256 bit `shuffle` work in  2 x 128 bit, but not the others! I will check this out more after work today, really cool! :)

**Comment by gustf** [comment]
Looks really good, very impressive!! 
The speedup on my macbook air is "only" 35% but that I think thats due to the fact that it is a macbook air :)
I have a lot to learn about SIMD, and this is teaching me a lot! Thank you! :) 
For me it is very tricky to juggle the 2x128 instructions and to get the shuffling right! :8ball:

**Comment by gustf** [comment]
Btw, I also experimented with an optimization that mimicked the inner loop iteration optimization. But since all 16 values `min[0:15] < diag[(i-1)+0:15]` had to be true, it probably did not happen very often and became around 30% slower instead. But it seemed to work though :)

**Comment by gustf** [comment]
Strange, I did an experiment with using insert instead in the function `_mm256_alignr_epi32_7`, which would enable us to only load 4 lines from diag/diag2. But that also was a slowdown.

```
__m256i _mm256_alignr_epi32_7(__m256i a, std::uint32_t v) {
  const __m256i rotl1_256_epi32 = _mm256_setr_epi32(7, 0, 1, 2, 3, 4, 5, 6);
  __m256i combined = _mm256_insert_epi32(a, (__int32_t)v, 7);
  //__m256i combined = _mm256_blend_epi32(a, b, 0x80);
  return _mm256_permutevar8x32_epi32(combined, rotl1_256_epi32);
}
```

Loading only 4 lines

```
__m256i diag_[4], diag2_[4];
std::uint32_t d_[4], d2_[4];
for (k = 0; k < 4; ++k) {
   diag_ [k] = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(&diag [i-7-k*8]));
   d_[k] = diag[i-8-k*8];
}
for (k = 0; k < 4; ++k) {
  diag2_[k] = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(&diag2[i-7-k*8]));
   d2_[k] = diag2[i-8-k*8];
 }
```

And then using them here

```
__m256i diag2_i_m1 = _mm256_alignr_epi32_7(diag2_[k], d2_[k]);
__m256i diag_i_m1  = _mm256_alignr_epi32_7(diag_ [k], d_ [k]);
```

And sorry for my spamming, I just think this is really fun :) Never played with SIMD before.

**Comment by addaleax** [comment]
No problem, I completely understand how one falls in love with SIMD ;) I guess you already found [Intel’s Intrinsics Guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide/), but just in case you haven’t, it’s an awesome reference for these functions.

And regarding your last experiment: How noticeable was the slowdown? I’d have guessed it wouldn’t make much of a difference, since the speed of memory access is usually determined by CPU cache organization, and since the access pattern stays the same, that should not have much of an impact? If there was a large difference, I’d definitely be curious why!

**Comment by addaleax** [comment]
Ah, btw: There is no single instruction corresponding to `_mm256_insert_epi32`:

``` c
#include <immintrin.h>

__m256i test(__m256i a, int i) {
  return _mm256_insert_epi32(a, i, 7);
}
```

becomes:

``` asm
$ gcc -O3 -mavx2 -c test.c && objdump -d test.o
0000000000000000 <test>:
   0:   c4 e3 7d 39 c1 01       vextracti128 $0x1,%ymm0,%xmm1
   6:   c4 e3 71 22 cf 03       vpinsrd $0x3,%edi,%xmm1,%xmm1
   c:   c4 e3 7d 38 c1 01       vinserti128 $0x1,%xmm1,%ymm0,%ymm0
  12:   c3                      retq   
```

So `_mm256_insert_epi32` actually expands as `_mm256_extracti128_si256 + _mm_insert_epi32 + _mm256_inserti128_si256`. I guess it makes sense then that there’s no speedup gained by using it.

**Comment by gustf** [comment]
Ah nice catch! The slowdown makes sense then. :)

Glad you are ok with my spamming :) Thanks.

**Pull request closed without merging**
